default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mauzo_be_dev

test:
  <<: *default
  database: mauzo_be_test

production:
  <<: *default
  database: mauzo_be_prod
  username: mauzo_be
  password: <%= ENV["MAUZO_BE_DATABASE_PASSWORD"] %>
